name: magento-test-framework
on: [pull_request]
jobs:
  functional:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: 8.1
      MAGENTO_HOST_NAME: localhost
      SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      mysql:
        image: bitnami/mysql:8.0.31
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: openmage
          MYSQL_PASSWORD: openmage
          MYSQL_DATABASE: openmage
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      selenium:
        image: selenium/standalone-chrome
        # options: --health-cmd "curl http://selenium:4444" --health-interval=5s
        ports:
          - 4444:4444

    steps:
      - name: Checkout OpenMage repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ctype, curl, dom, gd, hash, iconv, intl, json, libxml, mbstring, pdo_mysql, xml, soap, zlib

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Verify MySQL connection
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"localhost" -P"$DB_PORT" --silent; do
            sleep 1
          done          

      - name: Install Magento
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          sudo chmod 777 app/etc var/ media/
          php -f install.php -- \
            --license_agreement_accepted yes \
            --locale en_US --timezone "America/Los_Angeles" --default_currency USD \
            --db_host mysql:${DB_PORT} --db_name openmage --db_user openmage --db_pass openmage \
            --url "http://${MAGENTO_HOST_NAME}/" --use_rewrites yes --use_secure no \
            --secure_base_url "http://${MAGENTO_HOST_NAME}/" --use_secure_admin no \
            --admin_lastname Owner --admin_firstname Store --admin_email "admin@example.com" \
            --admin_username admin --admin_password 123123q123123q \
            --encryption_key "I2V7t7fiCIRKw9FWz4m3CStgeBG1T+ATZ0Us+W8jAIk="

      - name: Install PHPUnit Dependencies
        working-directory: ./dev/tests/functional
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - uses: dominicwatson/github-action-envsubst@v1
        with:
          files: .github/mtf/apache_virtual_host
          patterns: $GITHUB_WORKSPACE $MAGENTO_HOST_NAME $PHP_VERSION

      - name: Start Web Server
        run: |
          sudo cp -f .github/mtf/apache_virtual_host /etc/apache2/sites-enabled/000-default.conf
          #sudo cp -f .github/mtf/www.conf /usr/local/etc/php-fpm.d/www.conf
          cat /usr/local/etc/php-fpm.d/www.conf
          sudo php-fpm -t
          sudo chown -R www-data:www-data .
          sudo systemctl start apache2
          sudo systemctl start php${{ env.PHP_VERSION}}-fpm
          curl http://$MAGENTO_HOST_NAME

      - name: Setup and check MTF
        working-directory: ./dev/tests/functional
        run: |
          cp ./phpunit.xml.dist ./phpunit.xml
          sed -e "s?localhost?${MAGENTO_HOST_NAME}?g" --in-place ./phpunit.xml
          sed -e "s?basic?travis_acceptance?g" --in-place ./phpunit.xml
          php -f utils/generate.php
          cd ./utils
          php -f mtf troubleshooting:check-all

      - name: Run PHPUnit
        working-directory: ./dev/tests/functional
        run: vendor/phpunit/phpunit/phpunit

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.40
        if: always()
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: output/*.xml
